### ISSUE TITLE
Change library to uzers from users, change atty usage to std::io::IsTerminal

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/cli#19]
See title. Need to swap out dependencies and move from atty to rust standard library.

**Comment by eXhumer** [comment]
> move from atty to rust standard library.

I assume you mean replace `flexi_logger`? `atty` isn't a direct dependency of `decky` cli. It is a dependency of `flexi_logger`.

**Comment by TrainDoctor** [comment]
Closed with merge of #21.
